def fetch_all_glue_data(job_name):
    print("Fetching Glue data for: " + job_name)
    return {
        "job_config": {
            "name": job_name,
            "worker_type": "G.1X",
            "num_workers": 10,
            "glue_version": "4.0",
            "max_retries": 2,
            "timeout_min": 2880,
        },
        "run_history": [
            {
                "run_id": "jr_001",
                "status": "SUCCEEDED",
                "started": "2026-06-27 08:00",
                "duration_min": 14.2,
                "dpu": 10,
                "cost_usd": 0.52,
                "error": "",
            },
            {
                "run_id": "jr_002",
                "status": "SUCCEEDED",
                "started": "2026-06-26 08:00",
                "duration_min": 11.8,
                "dpu": 10,
                "cost_usd": 0.43,
                "error": "",
            },
            {
                "run_id": "jr_003",
                "status": "FAILED",
                "started": "2026-06-25 08:00",
                "duration_min": 2.1,
                "dpu": 10,
                "cost_usd": 0.08,
                "error": "EntityNotFoundException: Table not found",
            },
            {
                "run_id": "jr_004",
                "status": "SUCCEEDED",
                "started": "2026-06-24 08:00",
                "duration_min": 16.7,
                "dpu": 10,
                "cost_usd": 0.61,
                "error": "",
            },
            {
                "run_id": "jr_005",
                "status": "FAILED",
                "started": "2026-06-23 08:00",
                "duration_min": 2.3,
                "dpu": 10,
                "cost_usd": 0.09,
                "error": "AccessDeniedException: S3 access denied",
            },
            {
                "run_id": "jr_006",
                "status": "SUCCEEDED",
                "started": "2026-06-22 08:00",
                "duration_min": 13.5,
                "dpu": 10,
                "cost_usd": 0.49,
                "error": "",
            },
            {
                "run_id": "jr_007",
                "status": "SUCCEEDED",
                "started": "2026-06-21 08:00",
                "duration_min": 12.1,
                "dpu": 10,
                "cost_usd": 0.44,
                "error": "",
            },
            {
                "run_id": "jr_008",
                "status": "SUCCEEDED",
                "started": "2026-06-20 08:00",
                "duration_min": 15.3,
                "dpu": 10,
                "cost_usd": 0.56,
                "error": "",
            },
            {
                "run_id": "jr_009",
                "status": "FAILED",
                "started": "2026-06-19 08:00",
                "duration_min": 1.9,
                "dpu": 10,
                "cost_usd": 0.07,
                "error": "EntityNotFoundException: Database not found",
            },
            {
                "run_id": "jr_010",
                "status": "SUCCEEDED",
                "started": "2026-06-18 08:00",
                "duration_min": 13.9,
                "dpu": 10,
                "cost_usd": 0.51,
                "error": "",
            },
        ],
        "summary": {
            "total_runs": 10,
            "failed_runs": 3,
            "total_cost_usd": 3.85,
            "avg_duration_min": 10.5,
        },
    }
